- name: Download grafana deb file
  get_url:
    url="https://dl.grafana.com/oss/release/{{ grafana_filename }}"
    dest="/tmp/{{ grafana_filename }}"

- name: Verify grafana deb file
  command: dpkg-deb -W --showformat='${version}' /tmp/{{ grafana_filename }}
  register: grafana_deb_check_version
  failed_when: grafana_deb_check_version.stdout != "{{ grafana_version }}"

- name: Install grafana
  apt: deb="/tmp/{{ grafana_filename }}" state=present

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://remoteIP:3000
    method: GET
    status_code: 200
